# -*- coding: utf-8 -*-
"""ITCS 5154 project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2GbjOoVZjyn_xuWpORSAYXNlRVvoQav
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q transformers datasets scikit-learn tqdm pandas

import numpy as np
import pandas as pd
from tqdm import tqdm
from collections import Counter

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from datasets import load_dataset
from transformers import BertTokenizer, BertModel
from torch.optim import AdamW
from sklearn.metrics import accuracy_score, classification_report

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

MAX_LEN = 128
BATCH_SIZE = 16
EPOCHS = 2
LR = 3e-5
NUM_CLASSES = 2
MODEL_NAME = "bert-base-uncased"

dataset = load_dataset("imdb")

train_df = pd.DataFrame(dataset["train"])
test_df = pd.DataFrame(dataset["test"])

print(train_df.head())
print(train_df["label"].value_counts())
print(test_df["label"].value_counts())

train_df_small = pd.concat([
    train_df[train_df["label"] == 0].sample(2000, random_state=42),
    train_df[train_df["label"] == 1].sample(2000, random_state=42)
]).sample(frac=1, random_state=42).reset_index(drop=True)

test_df_small = pd.concat([
    test_df[test_df["label"] == 0].sample(500, random_state=42),
    test_df[test_df["label"] == 1].sample(500, random_state=42)
]).sample(frac=1, random_state=42).reset_index(drop=True)

print(train_df_small.shape, test_df_small.shape)
print(train_df_small["label"].value_counts())
print(test_df_small["label"].value_counts())

tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)

class ReviewDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len):
        self.texts = texts.tolist() if isinstance(texts, pd.Series) else texts
        self.labels = labels.tolist() if isinstance(labels, pd.Series) else labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = int(self.labels[idx])

        encoding = self.tokenizer(
            text,
            add_special_tokens=True,
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_attention_mask=True,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "label": torch.tensor(label, dtype=torch.long)
        }

train_dataset = ReviewDataset(
    train_df_small["text"],
    train_df_small["label"],
    tokenizer,
    MAX_LEN
)

test_dataset = ReviewDataset(
    test_df_small["text"],
    test_df_small["label"],
    tokenizer,
    MAX_LEN
)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

print(len(train_loader), len(test_loader))

class BertBiLSTMClassifier(nn.Module):
    def __init__(self, num_classes, lstm_hidden_size=128, lstm_layers=1, dropout=0.3, freeze_bert=False):
        super(BertBiLSTMClassifier, self).__init__()

        self.bert = BertModel.from_pretrained(MODEL_NAME)

        if freeze_bert:
            for param in self.bert.parameters():
                param.requires_grad = False

        self.bilstm = nn.LSTM(
            input_size=768,
            hidden_size=lstm_hidden_size,
            num_layers=lstm_layers,
            batch_first=True,
            bidirectional=True
        )

        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(lstm_hidden_size * 2, num_classes)

    def forward(self, input_ids, attention_mask):
        bert_outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        last_hidden_state = bert_outputs.last_hidden_state
        cls_embedding = last_hidden_state[:, 0, :]
        lstm_input = cls_embedding.unsqueeze(1)

        _, (hidden, _) = self.bilstm(lstm_input)

        forward_hidden = hidden[-2, :, :]
        backward_hidden = hidden[-1, :, :]

        combined_hidden = torch.cat((forward_hidden, backward_hidden), dim=1)
        x = self.dropout(combined_hidden)
        logits = self.fc(x)

        return logits

model = BertBiLSTMClassifier(num_classes=NUM_CLASSES, freeze_bert=False).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = AdamW(model.parameters(), lr=LR, eps=1e-8)

print(sum(p.numel() for p in model.parameters()))

def train_epoch(model, data_loader, optimizer, criterion, device):
    model.train()
    total_loss = 0
    all_preds = []
    all_labels = []

    for batch in tqdm(data_loader):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad()

        outputs = model(input_ids, attention_mask)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        preds = torch.argmax(outputs, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(data_loader)
    acc = accuracy_score(all_labels, all_preds)

    return avg_loss, acc

def eval_model(model, data_loader, criterion, device):
    model.eval()
    total_loss = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for batch in tqdm(data_loader):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)

            outputs = model(input_ids, attention_mask)
            loss = criterion(outputs, labels)

            total_loss += loss.item()

            preds = torch.argmax(outputs, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(data_loader)
    acc = accuracy_score(all_labels, all_preds)

    return avg_loss, acc, all_preds, all_labels

best_val_acc = 0.0

for epoch in range(EPOCHS):
    print(f"\nEpoch {epoch + 1}/{EPOCHS}")

    train_loss, train_acc = train_epoch(model, train_loader, optimizer, criterion, device)
    val_loss, val_acc, val_preds, val_labels = eval_model(model, test_loader, criterion, device)

    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"Val Loss:   {val_loss:.4f} | Val Acc:   {val_acc:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), "best_bert_bilstm_imdb.pt")
        print("Best model saved.")

print(classification_report(val_labels, val_preds, digits=4))

def predict_reviews(model, texts, tokenizer, device, max_len=128):
    model.eval()
    predictions = []

    with torch.no_grad():
        for text in texts:
            encoding = tokenizer(
                text,
                add_special_tokens=True,
                max_length=max_len,
                padding="max_length",
                truncation=True,
                return_attention_mask=True,
                return_tensors="pt"
            )

            input_ids = encoding["input_ids"].to(device)
            attention_mask = encoding["attention_mask"].to(device)

            outputs = model(input_ids, attention_mask)
            pred = torch.argmax(outputs, dim=1).item()
            predictions.append(pred)

    return predictions

sample_reviews = [
    "This movie was absolutely amazing and beautifully acted.",
    "The acting was horrible and the plot was boring.",
    "It had some good moments but overall felt weak."
]

preds = predict_reviews(model, sample_reviews, tokenizer, device, MAX_LEN)
print(preds)

def overall_polarity_binary(predictions):
    counts = Counter(predictions)

    positive = counts.get(1, 0)
    negative = counts.get(0, 0)

    if positive >= 1.2 * negative:
        return "positive"
    elif negative >= 1.2 * positive:
        return "negative"
    else:
        return "neutral"

overall = overall_polarity_binary(preds)
print("Overall polarity:", overall)

label_map = {0: "negative", 1: "positive"}

for text, pred in zip(sample_reviews, preds):
    print(label_map[pred], "->", text)